### ISSUE TITLE
sprite-url function generates sprite image several times

### ISSUE THREAD

**Issue by yoonsy** [AdamBrodzinski/Retina-Sprites-for-Compass#40]
I'm developing on Rails framework ver 3.2.13.

On development environment, [sprite-url](https://github.com/AdamBrodzinski/Retina-Sprites-for-Compass/blob/master/_retina-sprites.scss#L23) function generates sprite image several times. So, it takes long time to precompile scss file.

For example, `application.scss` file looks like below.

``` scss
@import "retina-sprites";
$sprites: sprite-map('to_sprite/*.png', $spacing: 1px);
$sprites2x: sprite-map('to_sprite/*.png', $spacing: 2px);

#logo {
  @include retina-sprite(logo);
}
#icon1 {
  @include retina-sprite(icon1);
}
#icon2 {
  @include retina-sprite(icon2);
}
```

I used `retina-sprite` mixin 3 times. 

It causes generating sprite image 3 times.
